### ISSUE TITLE
App doesn't run

### ISSUE THREAD

**Issue by brbergami** [rhysd/Tui#2]
Win 10 Pro build 16299.309 x64

The app crashes after first run as seen in screenshot
![image](https://user-images.githubusercontent.com/37002893/38500443-cb166698-3be0-11e8-8dea-cf8d7a3b1485.png)

Running lastest version from GitHub Tui-win32-x64

**Comment by rhysd** [comment]
It seems that a package is broken. I recreated packages. Is this still broken? https://github.com/rhysd/Tui/releases/tag/v0.4.17

**Comment by brbergami** [comment]
Let me try it.. 😃

**Comment by brbergami** [comment]
I downloaded from the link and still not running.. the output looks like the same:
![image](https://user-images.githubusercontent.com/37002893/38741895-6ff65b54-3f11-11e8-8c1c-18d073ed47fa.png)
I feel like an idiot.. is just me or is a known bug? 😆 

(Tui-win32-x64-0.4.17.zip)

Maybe my Windows theme is messing around with this? I wonder if the error comes when the app tries to draw the window. Never had a problem of this kind with any other app, tho

**Comment by rhysd** [comment]
Thank you for conforming it. I'll investigate this. Let me have time

**Comment by rhysd** [comment]
I noticed that npm and electron-packager behaviors were changed. I addressed it at a8556b8. Could you try the asset again? I recreated package again.

https://github.com/rhysd/Tui/releases/tag/v0.4.17

**Comment by brbergami** [comment]
Finally working.
![image](https://user-images.githubusercontent.com/37002893/38761719-8e734552-3f5b-11e8-9176-b74d05f3ac32.png)
